ui: tape
browsers:
  - name: ie
    version: 8..latest
  - name: firefox
    version: [31..latest, dev]
  - name: chrome
    version: [27..latest, dev]
  - name: opera
    version: [11..latest, next]
  - name: safari
    version: 5..latest
  - name: ipad
    version: 7.1..latest
  - name: iphone
    version: 7.1..latest
  - name: android
    version: 4.4..latest
browserify:
  - transform: .
  - require: ./index.js
    expose: sassify
    entry: false